version: 2.1


orbs:
  docker: circleci/docker@1.7.0

jobs:
  build-affected-docker-images-and-push:
    docker: 
      - image: 'node:lts-alpine3.14'
    environment:
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${AELP_APP_GOOGLE_CLIENT_ID}
      NEXT_PUBLIC_GRAPHQL_API_ENDPOINT: ${AELP_APP_GRAPHQL_API_ENPOINT}
    steps:
      - checkout
      - docker/install-docker
      - run: echo $AELP_APP_DOCKER_PASSWORD | docker login ghcr.io -u $AELP_APP_DOCKER_USERNAME --password-stdin
      - run: yarn nx affected --target=docker --skip-nx-cache

workflows:
  deploy-docker: 
    jobs:
      - build-affected-docker-images-and-push
