version: 2.1

jobs:
  build-affected-docker-images-and-push:
    docker:
      - image: 'node:lts-alpine3.14'
    steps:
      - checkout
      - run: apk add docker-cli git curl jq
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run: echo "$AELP_APP_DOCKER_PASSWORD" | docker login ghcr.io -u $AELP_APP_DOCKER_USERNAME --password-stdin
      - run: curl -s https://circleci.com/api/v1.1/project/github/aelporg/aelp-app?circle-token=$CIRCLE_CI_PAT | jq '[.[] | select(.status=="success" or .status=="fixed")] | max_by(.build_num).vcs_revision
      - run: export LAST_SUCCESSFUL_COMMIT=$(curl -s https://circleci.com/api/v1.1/project/github/aelporg/aelp-app?circle-token=$CIRCLE_CI_PAT | jq '[.[] | select(.status=="success" or .status=="fixed")] | max_by(.build_num).vcs_revision')
      - run: echo $CIRCLE_CI_PAT
      - run: echo $LAST_SUCCESSFUL_COMMIT
      - run: |
          export NEXT_PUBLIC_GOOGLE_CLIENT_ID=$AELP_APP_GOOGLE_CLIENT_ID
          export NEXT_PUBLIC_GRAPHQL_API_ENDPOINT=$AELP_APP_GRAPHQL_API_ENPOINT
      - run: yarn nx affected --target=docker --skip-nx-cache --base=$LAST_SUCCESSFUL_COMMIT --head=origin/master

workflows:
  deploy-docker:
    jobs:
      - build-affected-docker-images-and-push:
          context:
            - aelp-app
