version: 2.1


orbs:
  node: circleci/node@5.0
  docker: circleci/docker@1.7.0

jobs:
  build-affected-docker-images-and-push:
    docker: 
      - image: 'cimg/base:stable'
    environment:
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${AELP_APP_GOOGLE_CLIENT_ID}
      NEXT_PUBLIC_GRAPHQL_API_ENDPOINT: ${AELP_APP_GRAPHQL_API_ENPOINT}
    steps:
      - checkout
      - node/install-yarn:
          version: berry
      - node/install-packages:
          pkg-manager: yarn 
      - docker/install-docker
      - run: yarn nx affected --target=docker --skip-nx-cache

workflows:
  deploy-docker: 
    jobs:
      - build-affected-docker-images-and-push
