version: '3.9'
services:
  workspace:
    build:
      context: ../
      dockerfile: ./docker/workspace.Dockerfile
    # access docker daemon in the container
    volumes:
      - ..:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: node
  piston:
    image: ghcr.io/engineer-man/piston
    volumes:
      - piston-data:/piston
    tmpfs:
      - /piston/jobs
    environment:
      - PISTON_LOG_LEVEL=DEBUG
    restart: always
  posgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=aelpcore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=mypassword
    restart: always

volumes:
  postgres-data:
  piston-data:
